# Generated by Django 2.1.3 on 2019-03-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0002_characterchoose_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100, verbose_name='进度')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='游戏')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '游戏进程表',
                'verbose_name_plural': '游戏进程表',
            },
        ),
    ]
