# Generated by Django 2.1.3 on 2019-03-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0003_gameprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'scales', 'verbose_name_plural': 'scales'},
        ),
        migrations.AlterModelOptions(
            name='characterchoose',
            options={'verbose_name': 'tension_scale', 'verbose_name_plural': 'tension_scale'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'games', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='gameprocess',
            options={'verbose_name': 'progress', 'verbose_name_plural': 'progress'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'players', 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelOptions(
            name='playerscore',
            options={'verbose_name': 'voting', 'verbose_name_plural': 'voting'},
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, verbose_name='scale'),
        ),
        migrations.AlterField(
            model_name='characterchoose',
            name='character_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_one', to='arkserver.Character', verbose_name='scale_one'),
        ),
        migrations.AlterField(
            model_name='characterchoose',
            name='character_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_two', to='arkserver.Character', verbose_name='scale_two'),
        ),
        migrations.AlterField(
            model_name='characterchoose',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game'),
        ),
        migrations.AlterField(
            model_name='characterchoose',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='chooser'),
        ),
        migrations.AlterField(
            model_name='characterchoose',
            name='status',
            field=models.IntegerField(choices=[(0, 'nomal'), (1, 'showed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=200, verbose_name='game_name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='game_password'),
        ),
        migrations.AlterField(
            model_name='game',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_game', to='arkserver.Player', verbose_name='creater'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'nomal'), (1, 'end')], default=0, verbose_name='game_status'),
        ),
        migrations.AlterField(
            model_name='gameprocess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game'),
        ),
        migrations.AlterField(
            model_name='gameprocess',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Player', verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='gameprocess',
            name='process',
            field=models.CharField(max_length=100, verbose_name='progress'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_name',
            field=models.CharField(max_length=200, verbose_name='game_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='game_password'),
        ),
        migrations.AlterField(
            model_name='player',
            name='inviter_name',
            field=models.CharField(max_length=200, verbose_name='creater'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='player_name'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='arkserver.Player', verbose_name='voted_person'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='score',
            field=models.CharField(max_length=100, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_score', to='arkserver.Player', verbose_name='voting_person'),
        ),
    ]
