# Generated by Django 2.1.3 on 2019-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0005_firstscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=100, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='player',
            name='unionid',
            field=models.CharField(default='', max_length=100, verbose_name='unionid'),
        ),
    ]
