# Generated by Django 2.1.3 on 2019-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0006_auto_20190325_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='unionid',
        ),
        migrations.AddField(
            model_name='player',
            name='openid',
            field=models.CharField(default='', max_length=100, verbose_name='openid'),
        ),
    ]
