# Generated by Django 2.1.3 on 2019-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0007_auto_20190325_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'start'), (1, 'running'), (2, 'end')], default=0, verbose_name='game_status'),
        ),
    ]
