# Generated by Django 2.1.3 on 2019-03-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0008_auto_20190327_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.CharField(max_length=500, verbose_name='love')),
                ('add', models.CharField(max_length=500, verbose_name='add')),
                ('ask', models.CharField(max_length=500, verbose_name='ask')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkserver.Game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='arkserver.Player', verbose_name='player')),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to='arkserver.Player', verbose_name='teammate')),
            ],
        ),
    ]
