# Generated by Django 2.1.3 on 2019-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0011_auto_20190513_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='img',
            field=models.FileField(upload_to='result/'),
        ),
    ]
