# Generated by Django 2.1.3 on 2019-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0012_auto_20190513_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='game_secret',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='inviter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='result',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='result',
            name='img',
            field=models.FileField(default='', upload_to='result/'),
        ),
    ]
