# Generated by Django 2.1.3 on 2019-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkserver', '0013_auto_20190514_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='img',
            field=models.FileField(upload_to='result/'),
        ),
    ]
